apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: standard
  selector:
    matchLabels:
      name: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Mi