apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
        - image: mohamad2000/curl-alpine:1.0
          name: curl-alpine
          command: [ "/bin/sleep" ]
          args: [ "infinite" ]
          resources: {}

status: {}
